oscIn:
  ip: 10.1.10.203
  port: 8006

outputs:
  oscOut:
    ip: 10.1.10.77
    port: 8005
  midi-pc:
    name: UM-ONE
    channel: 1
  qlab: false 
  keyboard-commands: true
  audio-files: true

# 8x10s sound cues and Mic Mute/Unmute

control-cue-mapping:
  - light: 10.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_firstknock.mp3"
  - light: 15.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_twoknocks.mp3"
  - light: 20.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_oneknock.mp3"
  - light: 25.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_morseknocks.mp3"
  - light: 30.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_twoknocks.mp3"
  - light: 35.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_oneknock.mp3"
  - light: 40.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_oneknock.mp3"
  - light: 45.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_oneknock.mp3"
  - light: 50.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_oneknock.mp3"
  - light: 55.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_oneknock.mp3"
  - light: 60.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_oneknock.mp3"
  - light: 65.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\broadway_oneknock.mp3"
  - light: 85.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\supermarket_background.mp3"
  - light: 90.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\supermarket_pen.mp3"
  - light: 110.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\bread_opening.mp3"
  - light: 165.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\writing_background.mp3"
  - light: 180.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\writing_cartoon.mp3"
  - light: 205.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\explaining_crash.mp3"
  - light: 215.0
    unmute: [14]
  - light: 220.0
    mute: [14]
  - light: 225.0
    unmute: [14]
  - light: 230.0
    mute: [14]
  - light: 235.0
    unmute: [14]
  - light: 240.0
    mute: [14]
  - light: 245.0
    unmute: [14]
  - light: 250.0
    mute: [14]
  - light: 255.0
    unmute: [14]
  - light: 260.0
    mute: [14]
  - light: 265.0
    unmute: [14]
  - light: 270.0
    mute: [14]
  - light: 285.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\audience_background.mp3"
  - light: 290.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\audience_ringtone.mp3"
  - light: 310.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\three_birds.mp3"
  - light: 325.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\three_birds.mp3"
  - light: 340.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\melodrama_music.mp3"
  - light: 350.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\melodrama_sting.mp3"
  - light: 355.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\melodrama_carriage.mp3"
  - light: 360.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\melodrama_knock.mp3"
  - light: 375.0
    file: "C:\\Users\\LALT\\Documents\\Shows\\8x10_2025\\test\\melodrama_gun.mp3"
  
